server:
  port: 8081   # Puerto distinto para evitar conflictos

spring:
  application:
    name: ms-gateway-admin
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-catalogo
          uri: lb://ms-catalogo
          predicates:
            - Path=/categoria/**
          # filters:
          #   - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
